# - Find Jupyter instalation
# This module tries to find the Jupyter installation on your system.

FIND_PROGRAM(JUPYTER_EXECUTABLE NAMES jupyter)
SET(JUPYTER_FOUND False)
IF(NOT ${JUPYTER_EXECUTABLE} MATCHES "JUPYTER_EXECUTABLE-NOTFOUND")
    SET(JUPYTER_FOUND True)
    MESSAGE("-- Found Jupyter: " ${JUPYTER_EXECUTABLE})
ENDIF(NOT ${JUPYTER_EXECUTABLE} MATCHES "JUPYTER_EXECUTABLE-NOTFOUND")

FIND_PROGRAM(NBCONVERT_EXECUTABLE NAMES jupyter-nbconvert)
SET(NBCONVERT_FOUND False)
IF(NOT ${NBCONVERT_EXECUTABLE} MATCHES "NBCONVERT_EXECUTABLE-NOTFOUND")
    SET(NBCONVERT_FOUND True)
    MESSAGE("-- Found nbconvert: " ${NBCONVERT_EXECUTABLE})
ENDIF(NOT ${NBCONVERT_EXECUTABLE} MATCHES "NBCONVERT_EXECUTABLE-NOTFOUND")
